<?php
/**
 * @package PridgeWPEndpoint
 *
 * @var array<string, mixed> $integration_settings
 * @var bool                 $woocommerce_active
 * @var bool                 $germanized_available
 * @var bool                 $shiptastic_available
 * @var array<string,string> $order_statuses
 * @var array<string,string> $shipment_statuses
 * @var int[]                $cron_intervals
 */
defined( 'ABSPATH' ) || exit;
?>
<form class="pridge-settings-form" action="options.php" method="post">
	<?php settings_fields( 'pridge_wp_integrations_group' ); ?>
	<section class="pridge-panel is-visible">
		<div class="pridge-panel-heading"><div><span class="pridge-kicker"><?php esc_html_e( 'Commerce engine', 'pridge-wp-endpoint' ); ?></span><h2><?php esc_html_e( 'WooCommerce', 'pridge-wp-endpoint' ); ?></h2><p><?php esc_html_e( 'Enable order-driven document printing without affecting checkout.', 'pridge-wp-endpoint' ); ?></p></div></div>
		<div class="pridge-toggle-row <?php echo $woocommerce_active ? '' : 'is-disabled'; ?>"><div><strong><?php esc_html_e( 'WooCommerce integration', 'pridge-wp-endpoint' ); ?></strong><span><?php echo $woocommerce_active ? esc_html__( 'WooCommerce is active and HPOS-compatible printing is available.', 'pridge-wp-endpoint' ) : esc_html__( 'WooCommerce is not active.', 'pridge-wp-endpoint' ); ?></span></div><label class="pridge-switch"><span class="screen-reader-text"><?php esc_html_e( 'Enable WooCommerce integration', 'pridge-wp-endpoint' ); ?></span><input type="checkbox" name="pridge_wp_integrations[woocommerce_enabled]" value="1" data-pridge-woo-toggle <?php checked( ! empty( $integration_settings['woocommerce_enabled'] ) ); ?> <?php disabled( ! $woocommerce_active ); ?>><span aria-hidden="true"></span></label></div>
		<label class="pridge-field pridge-status-field"><span><?php esc_html_e( 'Print when order becomes', 'pridge-wp-endpoint' ); ?></span><select name="pridge_wp_integrations[trigger_status]" <?php disabled( ! $woocommerce_active ); ?>><?php foreach ( $order_statuses as $status_key => $status_label ) : $status_value = 0 === strpos( $status_key, 'wc-' ) ? substr( $status_key, 3 ) : $status_key; ?><option value="<?php echo esc_attr( $status_value ); ?>" <?php selected( $integration_settings['trigger_status'], $status_value ); ?>><?php echo esc_html( $status_label ); ?></option><?php endforeach; ?><?php if ( $shiptastic_available ) : ?><option value="shipped" <?php selected( $integration_settings['trigger_status'], 'shipped' ); ?>><?php esc_html_e( 'Shipped (Shiptastic)', 'pridge-wp-endpoint' ); ?></option><?php endif; ?></select><small><?php esc_html_e( 'Shipped follows Shiptastic’s order shipping status, not a WooCommerce order status.', 'pridge-wp-endpoint' ); ?></small></label>
		<label class="pridge-field pridge-status-field"><span><?php esc_html_e( 'After a successful print, set order status to', 'pridge-wp-endpoint' ); ?></span><select name="pridge_wp_integrations[post_print_woocommerce_status]" <?php disabled( ! $woocommerce_active ); ?>><option value=""><?php esc_html_e( 'No change', 'pridge-wp-endpoint' ); ?></option><?php foreach ( $order_statuses as $status_key => $status_label ) : $status_value = 0 === strpos( $status_key, 'wc-' ) ? substr( $status_key, 3 ) : $status_key; ?><option value="<?php echo esc_attr( $status_value ); ?>" <?php selected( $integration_settings['post_print_woocommerce_status'], $status_value ); ?>><?php echo esc_html( $status_label ); ?></option><?php endforeach; ?></select><small><?php esc_html_e( 'Applied once every routed document for the order has been sent. Must differ from the trigger status above.', 'pridge-wp-endpoint' ); ?></small></label>
	</section>
	<section class="pridge-panel is-visible">
		<div class="pridge-panel-heading"><div><span class="pridge-kicker"><?php esc_html_e( 'Optional legal integration', 'pridge-wp-endpoint' ); ?></span><h2><?php esc_html_e( 'Germanized', 'pridge-wp-endpoint' ); ?></h2><p><?php esc_html_e( 'Germanized can only be enabled while the WooCommerce integration is enabled.', 'pridge-wp-endpoint' ); ?></p></div></div>
		<div class="pridge-toggle-row <?php echo $germanized_available ? '' : 'is-disabled'; ?>"><div><strong><?php esc_html_e( 'Germanized integration', 'pridge-wp-endpoint' ); ?></strong><span><?php echo $germanized_available ? esc_html__( 'Germanized is active.', 'pridge-wp-endpoint' ) : esc_html__( 'Germanized for WooCommerce is not active.', 'pridge-wp-endpoint' ); ?></span></div><label class="pridge-switch"><span class="screen-reader-text"><?php esc_html_e( 'Enable Germanized integration', 'pridge-wp-endpoint' ); ?></span><input type="checkbox" name="pridge_wp_integrations[germanized_enabled]" value="1" data-pridge-germanized-toggle data-plugin-available="<?php echo $germanized_available ? '1' : '0'; ?>" <?php checked( ! empty( $integration_settings['germanized_enabled'] ) ); ?> <?php disabled( ! $germanized_available || empty( $integration_settings['woocommerce_enabled'] ) ); ?>><span aria-hidden="true"></span></label></div>
		<div class="pridge-fields-grid">
			<label class="pridge-field pridge-status-field"><span><?php esc_html_e( 'After a shipping label prints, set Shiptastic status to', 'pridge-wp-endpoint' ); ?></span><select name="pridge_wp_integrations[post_print_shiptastic_status]" <?php disabled( ! $shiptastic_available ); ?>><option value=""><?php esc_html_e( 'No change', 'pridge-wp-endpoint' ); ?></option><?php foreach ( $shipment_statuses as $status_key => $status_label ) : ?><option value="<?php echo esc_attr( $status_key ); ?>" <?php selected( $integration_settings['post_print_shiptastic_status'], $status_key ); ?>><?php echo esc_html( $status_label ); ?></option><?php endforeach; ?></select></label>
			<label class="pridge-field"><span><?php esc_html_e( 'Check for ready documents every', 'pridge-wp-endpoint' ); ?></span><select name="pridge_wp_integrations[cron_interval_minutes]"><?php foreach ( $cron_intervals as $minutes ) : ?><option value="<?php echo esc_attr( $minutes ); ?>" <?php selected( (int) $integration_settings['cron_interval_minutes'], $minutes ); ?>><?php echo esc_html( sprintf( /* translators: %d: minutes. */ _n( '%d minute', '%d minutes', $minutes, 'pridge-wp-endpoint' ), $minutes ) ); ?></option><?php endforeach; ?></select><small><?php esc_html_e( 'How often WP-Cron checks orders waiting on invoice, packing-slip, or label PDFs.', 'pridge-wp-endpoint' ); ?></small></label>
			<label class="pridge-field"><span><?php esc_html_e( 'Give up waiting after (hours)', 'pridge-wp-endpoint' ); ?></span><input type="number" min="1" max="168" name="pridge_wp_integrations[pending_timeout_hours]" value="<?php echo esc_attr( $integration_settings['pending_timeout_hours'] ); ?>"><small><?php esc_html_e( 'An order still missing documents after this long is flagged on Overview for a shop manager to print manually.', 'pridge-wp-endpoint' ); ?></small></label>
		</div>
	</section>
	<div class="pridge-save-bar"><div><strong><?php esc_html_e( 'Integration switches', 'pridge-wp-endpoint' ); ?></strong><span><?php esc_html_e( 'Document destinations are configured under Endpoints & Routing.', 'pridge-wp-endpoint' ); ?></span></div><?php submit_button( __( 'Save integrations', 'pridge-wp-endpoint' ), 'primary pridge-button is-primary', 'submit', false ); ?></div>
</form>
